name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.14.0
          otp-version: 25
          version-type: "strict"

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
      - name: Check Code Format
        run: mix format --check-formatted

      - name: Run Tests
        run: MIX_ENV=test mix do coveralls.json

      - name: Generate docs
        run: mix docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
